modLoader="javafml"
loaderVersion="[1,)"
license="ARR"
issueTrackerURL="https://github.com/teaconmc/XKDeco/issues?q=is%3Aissue"

[[mods]]
modId="xkdeco"
authors="XeKr, Snownee, LittleBai, TeaConMC"
version="${file.jarVersion}"
displayName="XeKr's Decoration"
displayURL="https://www.curseforge.com/minecraft/mc-mods/xks-decoration"
description='''
Models and textures are created by XeKr: https://github.com/XeKr
'''

[[mixin]]
config="xkdeco.mixins.json"

[modproperties.xkdeco]
kiwiCustomization=true

[[dependencies.xkdeco]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.xkdeco]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.xkdeco]]
modId="kiwi"
type="required"
versionRange="[15.2.0-alpha,)"
ordering="NONE"
side="BOTH"