modLoader = "javafml"
loaderVersion = "[1,)"
license = "ARR"
issueTrackerURL = "https://github.com/teaconmc/XKDeco/issues?q=is%3Aissue"
mixins = [
    { config = "xkdeco.mixins.json" },
    { config = "xkdeco.data.mixins.json" },
]

[[mods]]
modId = "xkdeco"
authors = "XeKr, Snownee, LittleBai, TeaConMC"
credits = "ustc-zzzz, LucunJi, 3TUSK, TartaricAcid, IzzelAliz, Gu-ZT, SettingDust, a1640727878, xkball"
version = "${file.jarVersion}"
displayName = "XeKr's Decoration"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/xks-decoration"
description = "Models and textures are created by XeKr: https://github.com/XeKr"

[modproperties.xkdeco]
kiwiCustomization = true

[[dependencies.xkdeco]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.71,)"

[[dependencies.xkdeco]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"

[[dependencies.xkdeco]]
modId = "kiwi"
type = "required"
versionRange = "[26.0.8,)"

[[dependencies.xkdeco]]
modId = "jei"
type = "optional"
versionRange = "*"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/jei"

[[dependencies.xkdeco]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "*"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items"
