namespace: xkdeco
dest: ../src/kiwi_generated/resources
translation_file_name: '{}.json'
translation_dest: '%TEMP%/assets/xkdeco_extra/lang'
json_pretty_print: false
export_format: yaml
pack_version: '1.21'
materials:
  - xkdeco.xlsx
glass_types:
  - xkdeco.xlsx
block_templates:
  - xkdeco.xlsx
blocks:
  - xkdeco.xlsx
block_tags:
  - xkdeco.xlsx
item_templates:
  - xkdeco.xlsx
items:
  - xkdeco.xlsx
item_tags:
  - xkdeco.xlsx
creative_tabs:
  - xkdeco.xlsx
block_families:
  - xkdeco.xlsx
shapes:
  - exported_shapes.json
