name: test-build
on:
  push:
    paths:
      - 'kiwi-jiachen'
      - 'kiwi-jiachen/**'
      - 'src/**'
      - 'build.gradle'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Kiwi
        id: build-kiwi
        run: cd kiwi-jiachen && chmod +x gradlew && ./gradlew shadowJar
      - name : Copy Kiwi
        id: copy-kiwi
        run: mkdir libs && cp kiwi-jiachen/build/libs/* ./libs/
      - name: Build
        id: build
        run: ./gradlew build # publishReleasePublicationToTeaconRepository