name: XKDeco 1.21-NeoForge Nightly Build
on:
  push:
    paths:
      - 'kiwi-jiachen'
      - 'kiwi-jiachen/**'
      - 'src/**'
      - 'build.gradle'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Kiwi
        id: build-kiwi
        run: cd kiwi-jiachen && chmod +x gradlew && ./gradlew shadowJar
      - name : Copy Kiwi
        id: copy-kiwi
        run: mkdir libs && cp kiwi-jiachen/build/libs/* ./libs/
      - name: Build
        id: build
        env:
          ARCHIVE_ENDPOINT: ${{ secrets.TEACON_ARCHIVE_ENDPOINT }}
          ARCHIVE_ACCESS_KEY: ${{ secrets.TEACON_ARCHIVE_ACCESS_KEY }}
          ARCHIVE_SECRET_KEY: ${{ secrets.TEACON_ARCHIVE_SECRET_KEY }}
        run: ./gradlew -Dorg.gradle.s3.endpoint=$ARCHIVE_ENDPOINT publishReleasePublicationToTeaconRepository githubActionOutput
      - name: GitHub Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_path }}